/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainAtLifetimeRouteImport } from './routes/train-at-lifetime'
import { Route as IndexRouteImport } from './routes/index'

const TrainAtLifetimeRoute = TrainAtLifetimeRouteImport.update({
  id: '/train-at-lifetime',
  path: '/train-at-lifetime',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/train-at-lifetime': typeof TrainAtLifetimeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/train-at-lifetime': typeof TrainAtLifetimeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/train-at-lifetime': typeof TrainAtLifetimeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/train-at-lifetime'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/train-at-lifetime'
  id: '__root__' | '/' | '/train-at-lifetime'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrainAtLifetimeRoute: typeof TrainAtLifetimeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/train-at-lifetime': {
      id: '/train-at-lifetime'
      path: '/train-at-lifetime'
      fullPath: '/train-at-lifetime'
      preLoaderRoute: typeof TrainAtLifetimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrainAtLifetimeRoute: TrainAtLifetimeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
